### ISSUE TITLE
Add support for spot instances

### ISSUE THREAD

**Issue by MasterWayZ** [equinix/terraform-metal-vsphere#10]
Hi,

Would it be possible to add support for deploying the servers as a spot instance? This could reduce the costs for the servers for testing and such, assuming the spot price is lower than on demand, but that can be checked in the console.

**Comment by displague** [comment]
https://registry.terraform.io/providers/equinix/metal/latest/docs/resources/spot_market_request shows how spot market requests can be created


https://github.com/equinix/terraform-metal-vsphere/blob/master/main.tf#L116-L136 may need to be converted to a module that can toggle between spot and normal devices.

**Comment by MasterWayZ** [comment]
I've looked at that, however, converting it to a module is what I don't understand/get stuck at (mainly because I don't know Terraform), I've never made anything with Terraform or edited something, so not sure of how much use I am on this.

**Comment by displague** [comment]
Thanks for your previous interest in this project. 
I'm closing all open issues to deprecate and archive this project. 
See #65 for more details.
