### ISSUE TITLE
Introduce method to declare hardware reservations for esxi hosts

### ISSUE THREAD

**Issue by displague** [equinix/terraform-metal-vsphere#21]
It is common for users to modify this module to set `hardware_reservation_id = "next-available"`.

When these users run out of reservations, they will encounter errors stating as much.

It would be preferable to offer a variable to declare all esxi host reservations (and perhaps reservations for other nodes, such as the gateway, in the future).

At first glance, I believe this would work:
```hcl
// variables.tf
variable "esxi_host_reservations" {
  type = list(string)
  description = "Hardware reservation ids to use for esxi hosts. Must be empty, a valid UUID, or next-available."
  example = ["uuid", "next-available", "", "", "" ]
}

// main.tf 

resource "metal_device" "esxi_hosts" {
...
  hardware_reservation_id = try(var.esxi_host_reservations[count.index], null)
}
```

I'm not completely sure about this approach as I do not know how `hardware_reservation_id` handles empty strings (or null values).

The example may look more like: `["uuid", "next-available", null, null]`

We can also describe this field as not needing trailing null or `""` values. allowing for esxi hosts beyond the size of this variables to be drawn from on-demand resources.

**Comment by Michael-sfo** [comment]
I'm thinking that a name:value pair would be more useful.....like ["esx01","next-available"],["edge-gateway",""], .......

That would allow a bit fine control.

**Comment by Michael-sfo** [comment]
With the changes above and esxi_host_reservations = ["", "", "", "", "next-available"] in terraform.tfvars, all of the instances were still on-demand.

**Comment by displague** [comment]
> I'm thinking that a name:value pair would be more useful.....like ["esx01","next-available"],["edge-gateway",""], .......

The keys/names here could match the generated `metal_device.hostname` field which would make the lookup easy.
Map lookup misses result in `""`, so that's a nice perk over the array.

 HCL provides the necessary functions to expand this map with n nodes drawing from other local variables as needed.
