### ISSUE TITLE
error fetching ISO via minio client

### ISSUE THREAD

**Issue by displague** [equinix/terraform-metal-vsphere#50]
There have been some reports that the latest minio client is causing the ISO to fail to download correctly.

It has been suggested that a fix is to replace https://github.com/equinix/terraform-metal-vsphere/blob/b96face0faa50cf565281e8be5aac6c1e9fc1920/templates/download_vcenter.sh#L32 with a tagged release, for example:

```
curl -Lo mc https://dl.min.io/client/mc/release/linux-amd64/archive/mc.RELEASE.2022-01-07T06-01-38Z
```

Currently awaiting confirmation that this is a real bug or working solution.
Regardless, pinning to a fixed version of assets will provide greater reliability - verifying that asset against a known checksum would be even better.

**Comment by michaelheinsfo** [comment]
Change is good.  I just verified with a fresh pull + change as above

**Comment by displague** [comment]
The upstream issue is https://github.com/minio/mc/issues/3938
