### ISSUE TITLE
connect.SmartConnectNoSSL deprecated 

### ISSUE THREAD

**Issue by antonioribezzi-acc** [equinix/terraform-metal-vsphere#58]
I tried to use the module to deploy a vSphere cluster, I had the issue that `connect.SmartConnectNoSSL` is not present anymore in pyvmomi.
I managed to make it work by chaning this:
```
si = connect.SmartConnectNoSSL(
    host=esx_host, user=esx_user, pwd=esx_pass, port=443
)
```
to this:
```
si = connect.SmartConnect(
    host=esx_host, user=esx_user, pwd=esx_pass, port=443, disableSslCertValidation=True
)
```

**Comment by jastr945** [comment]
I ran into the same issue and the above solution worked for me. Thanks!

**Comment by displague** [comment]
Thanks for your previous interest in this project. 
I'm closing all open issues to deprecate and archive this project. 
See #65 for more details.
